website:
  sidebar:
  - contents:
    - reference/index.qmd
    - contents:
      - reference/Lifemap.qmd
      - reference/Lifemap.layer_points.qmd
      - reference/Lifemap.layer_lines.qmd
      - reference/Lifemap.layer_donuts.qmd
      - reference/Lifemap.layer_heatmap.qmd
      - reference/Lifemap.layer_screengrid.qmd
      - reference/Lifemap.show.qmd
      - reference/Lifemap.save.qmd
      section: Visualization
    - contents:
      - reference/aggregate_count.qmd
      - reference/aggregate_num.qmd
      - reference/aggregate_freq.qmd
      section: Data aggregation
    id: reference
  - id: dummy-sidebar
