---
title: "pylifemap"
---

## Overview

`pylifemap` is a Python package for visualizing taxonomy data on [Lifemap](https://lifemap.cnrs.fr), the interactive tree of life. It provides several visualization layers, as well as functions allowing to aggregate data along the tree branches. 

Here is a simple example:

```{python}
#| warning: false

import polars as pl
from pylifemap import Lifemap

# Load iucn dataset
iucn = pl.read_parquet(
    "https://raw.githubusercontent.com/Lifemap-ToL/pylifemap/main/data/iucn.parquet"
)

Lifemap(iucn).layer_points(radius=5, opacity=0.8).show()
```

## Installation and usage

- [Getting started](getting_started.qmd) gives an overview of the package usage and features.
- [Usage](usage.qmd) describes how to use the package and the available features and options.
- The *Layers* section shows examples of the different available layers.
- [Reference](reference/index.qmd) provides detailed documentation of the different methods and functions.

## Credits

- The `iucn` data files in the `data/` directory have been generated from [The IUCN Red List of Threatened Species](https://www.gbif.org/dataset/19491596-35ae-4a91-9a98-85cf505f1bd3) dataset (DOI [10.15468/0qnb58](https://doi.org/10.15468/0qnb58)).
- Visualizations are powered by [Open Layers](https://openlayers.org), [deck.gl](https://deck.gl), [d3](https://d3js.org) and [Observable Plot](https://observablehq.com/plot/).
- The widget is developed thanks to the [anywidget](https://anywidget.dev) framework.
- This documentation website is generated by [Quarto](https://quarto.org) and [quartodoc](https://github.com/machow/quartodoc).
