name: Tests

on:
    push:
        branches: [main]

jobs:
    python-tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

        steps:
            - name: Check out pylifemap repository
              uses: actions/checkout@v6

            - name: Setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: "npm"

            - name: Install node dependencies
              run: npm ci

            - name: Bundle
              run: npm run bundle

            - name: Install uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

            - name: Set up Python ${{ matrix.python-version }}
              run: uv python install ${{ matrix.python-version }}

            - name: Install the project
              run: uv sync --all-extras --dev

            - name: Run pytest
              run: uv run pytest
